site_name: Digital Domain Content Console
theme: readthedocs
theme_dir: readthedocs_overrides

pages:
- Home: index.md
- BASICS:
  - Features: venom\features.md
  - Site Organization: venom\siteorg.md
  - Search Tools: venom\searchtools.md
- ACCOUNT MANAGEMENT:
  - Staff Permissions: venom\permissions.md
  - Manage User Accounts: venom\accountmanage.md
- PREREQUISITES:
  - Video Publishing Requirements: venom\videopublishrequirements.md
  - Define Video Property: venom\createproperty.md
  - Define Video Collection: venom\createcollection.md
- PUBLISH VIDEOS:
  - Publish Hosted Video: venom\publishhostedvideo.md
  - Publish Live Stream: venom\publishlivestream.md
  - Publish External Video: venom\publishexternalvideo.md
  - Update Video Profile: venom\managevideo.md
- PUBLISH APPLICATIONS:
  - Publish Application: venom\publishapp.md
  - Update Application Profile: venom\manageapp.md
- ANALYTICS AND MONITORING:
  - Video Usage Analytics: venom\videousageanalytics.md
  - Content Console Monitoring: venom\contentconsolemonitoring.md
- LOCALIZATION: venom\localization.md
- TERMS: venom\terms.md
- LEGAL: venom\legal.md
- TECHNICAL FAQ: venom\techfaq.md
- SUPPORT: venom\support.md
