site_name: Digital Domain Content Console
theme: readthedocs
theme_dir: readthedocs_overrides

pages:
- Home: index.md
- BASICS:
  - Features: venom\features.md
  - Site Organization: venom\siteorg.md
  - Search Tools: venom\searchtools.md
  - Roadmap: venom\roadmap.md
- ACCOUNT MANAGEMENT:
  - Sign Up: venom\signup.md
  - Manage User Accounts: venom\accountmanage.md
  - Staff Permissions: venom\permissions.md
  - Manage Property: venom\manageproperty.md
- MEDIA PUBLISHING PREREQUISITES:
  - Media Publishing Requirements: venom\mediapublishrequirements.md
  - Create Property: venom\manageproperty.md
  - Create Collection: venom\managecollection.md
- PUBLISH VIDEOS:
  - Media Publishing Options: venom\mediapublishingoptions.md
  - Publish Hosted Video: venom\publishhostedvideo.md
  - Add Video Formats: venom\addvideoformats.md
  - Add Language: venom\addlanguage.md
  - Publish External Video: venom\publishexternalvideo.md
  - Manage Video: venom\managevideo.md
  - Technical FAQ (Video): venom\techfaqvideo.md
- PUBLISH LIVE EVENTS:
  - Publish Live Event: venom\publishliveevent.md
  - Add Language: venom\addlanguage.md
  - Add Multiple Live Stream Cameras: venom\addcamerastreams.md
  - Manage Live Event: venom\manageliveevent.md
- APPLICATION PUBLISHING PREREQUISITES:
  - Application Publishing Requirements: venom\apppublishrequirements.md
- PUBLISH APPLICATIONS:
  - Publish Application: venom\publishapp.md
  - Update Application Profile: venom\manageapp.md
  - Technical FAQ (Application): venom\techfaqapp.md
- ANALYTICS AND MONITORING:
  - Media Usage Analytics: venom\mediausageanalytics.md
  - Content Console Monitoring: venom\contentconsolemonitoring.md
- LOCALIZATION: venom\localization.md
- TERMINOLOGY: venom\terms.md
- LEGAL: venom\legal.md
- SUPPORT: venom\support.md
